version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::221703039902:user/aws-sam-cli-managed-dev-env-pipeline-PipelineUser-1S1DL7X24ABQZ"
permissions_provider = "AWS IAM"

[dev_env]
[dev_env.pipeline_bootstrap]
[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::221703039902:role/aws-sam-cli-managed-dev-env-PipelineExecutionRole-106T8LOGTE9V"
cloudformation_execution_role = "arn:aws:iam::221703039902:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionR-16SQREGPVLWKC"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-qxphs5th8ers"
image_repository = ""
region = "us-east-1"

[prod_env]
[prod_env.pipeline_bootstrap]
[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::221703039902:role/aws-sam-cli-managed-prod-env-PipelineExecutionRole-1DVVN7K40E7EL"
cloudformation_execution_role = "arn:aws:iam::221703039902:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1H225OZQAX9Q4"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-p6qd2nrgl54d"
image_repository = ""
region = "us-east-1"
